const REACT_APP_MOCK_SERVER_MODE = process.env.REACT_APP_MOCK_SERVER_MODE;

const REACT_APP_RELAY_API_ENDPOINT = process.env.REACT_APP_RELAY_API_ENDPOINT;
const REACT_APP_MOCK_API_ENDPOINT = process.env.REACT_APP_MOCK_API_ENDPOINT;

export const fetchEndpoint = !!+REACT_APP_MOCK_SERVER_MODE 
    ? REACT_APP_MOCK_API_ENDPOINT 
    : REACT_APP_RELAY_API_ENDPOINT;

const REACT_APP_RELAY_SUBSCRIPTION_ENDPOINT = process.env.REACT_APP_RELAY_SUBSCRIPTION_ENDPOINT;
const REACT_APP_MOCK_SUBSCRIPTION_ENDPOINT = process.env.REACT_APP_MOCK_SUBSCRIPTION_ENDPOINT;

export const subscriptionEndpoint = !!+REACT_APP_MOCK_SERVER_MODE 
    ? REACT_APP_MOCK_SUBSCRIPTION_ENDPOINT 
    : REACT_APP_RELAY_SUBSCRIPTION_ENDPOINT;
